# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 刘波的学习记录
brief-intro: Android Java C Coder
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liubocode.gitee.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: #推特账号
facebook_username: #脸书账号
github_username:  liubo11
email: liubo233@qq.com
weibo_username: #微博账号
zhihu_username: #知乎账号
linkedIn_username: #领英账号
dribbble_username: #设计师的交互平台

description_footer: 刘波的个人博客

# comments 评论系统已弃用

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: b659da8ed4e65e6090d2d6a718d56b8f
google_analytics_id: #UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001

destination: deploy

sass:
  sass_dir: _sass
  style: compressed